### PR TITLE
Remove API docs from README.md

### PR DESCRIPTION
**Pull request by annarieger**
Replace full documentaion in `README.md` by link to automatically generated API docs.

Please review @terrestris/devs

### CODE REVIEW

**Comment by dnlkoch** [comment]
Thanks for this @arieger!

Can you also include a link to the release version of the docs, e.g. https://terrestris.github.io/ol-util/3.0.0/index.html?

**Comment by annarieger** [comment]
> Can you also include a link to the release version of the docs, e.g. https://terrestris.github.io/ol-util/3.0.0/index.html?

Do you mean an additional link to last released version beside of `latest` or should the [`latest`](https://github.com/terrestris/ol-util/pull/151/files#diff-04c6e90faac2675aa89e2176d2eec7d8R17) link be better replaced by released one?

**Comment by dnlkoch** [comment]
I would suggest to just have one additional link besides the latest. Something like: Docs  for each version are available via the following format https://terrestris.github.io/ol-util/3.0.0/index.html

**Comment by annarieger** [comment]
> I would suggest to just have one additional link besides the latest. Something like: Docs for each version are available via the following format https://terrestris.github.io/ol-util/3.0.0/index.html

:+1: adjusted in force-pushed 284259c

**Pull request merged**
