### PR TITLE
terrestris#503 add mm to formatLength and formatArea

### PR DESCRIPTION
**Pull request by DieuAnh**
I added mm in format length and format area for the tooltip. It's needed for my work project. Please review. Thank you.

### CODE REVIEW

**Comment by marcjansen** [comment]
Thanks for the pull request.

Could you please add a test and update API documentation? Please ping us if you need help

**Comment by DieuAnh** [comment]
Thanks for your quick response. However, how can I add a test for this ? @marcjansen

**Comment by dnlkoch** [comment]
Hi @DieuAnh, thanks for you contribution!

The existing tests for the [formatLength()](https://github.com/terrestris/ol-util/blob/master/src/MeasureUtil/MeasureUtil.spec.ts#L55) and [formatArea()](https://github.com/terrestris/ol-util/blob/master/src/MeasureUtil/MeasureUtil.spec.ts#L101) methods might give you a good starting point. In principle a test should assert if an input value (e.g. a line with the length of 0.1 meters) will result in the expected output value (e.g. 100 mm).

**Comment by DieuAnh** [comment]
Hello @dnlkoch,
I updated the pr, could you please take a look ? Thanks

**Review by dnlkoch — APPROVED** [review]

**Comment by dnlkoch** [comment]
Thanks @DieuAnh!

**Pull request merged**
