### PR TITLE
Improve performance of getLayer functions

### PR DESCRIPTION
**Pull request by KaiVolland**
This refactors some key functions to use the filter argument of the `getAllLayers`. The layers only get iterated once now.

### CODE REVIEW

**Comment by marcjansen** [comment]
Great, could you please add tests that pass before and after. Thank you.

**Comment by KaiVolland** [comment]
There are tests, but it seems like they do not run via ci. :shrug:

**Comment by marcjansen** [comment]
`getLayerByOlUid` [seems to be untested](https://coveralls.io/builds/67259124/source?filename=src%2FMapUtil%2FMapUtil.ts#L141).

And CI obviously should run tests, shouldn't it?

**Comment by KaiVolland** [comment]
Actually it did run tests but included in the `npm run build`. I changed this behaviour in #1412 .

**Review by marcjansen — APPROVED** [review]
Good to be merged, thanks @KaiVolland

**Pull request merged**
