### PR TITLE
Support sources with URLs containing parameters

### PR DESCRIPTION
**Pull request by marcjansen**
Follow up of #19, see https://github.com/terrestris/ol-util/pull/19#discussion_r215292436

Please review.

### CODE REVIEW

**Comment by weskamm** [comment]
Nice addition!
So URLs ending with a `?` will get an `&` appended, right?
`https://ows.terrestris.de/osm/service?&SERVICE=WMS.....`
As far as i know, this should not be a problem, but not 100% sure.
Feel free to merge anyways!

**Comment by marcjansen** [comment]
> So URLs ending with a `?` will get an `&` appended, right?
> `https://ows.terrestris.de/osm/service?&SERVICE=WMS.....`

Yes.

> As far as i know, this should not be a problem, but not 100% sure.

Same here, I never experienced any bad behavior. If so we can always become smarter, I guess.

Thanks for the reviews.

**Comment by marcjansen** [comment]
How is this backported now?

**Comment by weskamm** [comment]
you can do it by checking out the ol4 branch, apply the patch and commit against ol4 branch.
Its up to you if you want to do it as we may remove that branch in the future anyways

**Comment by marcjansen** [comment]
I won't be able to do that and would love to have someone else take this duty from me, :wink:

**Pull request merged**
